### ISSUE TITLE
Feat: If any field remains empty after submitting then it must saves the already given answers by user .

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Open-Source-Chandigarh/Euphoria-Check#123]
### Describe the feature

When user gives answers of question and then hit submit but if some questions remains unanswered and it shows the warning then it must save the ans of the already given questions so that it can save lot of time of the user .

### Add ScreenShots

https://github.com/Open-Source-Chandigarh/Euphoria-Check/assets/118350936/31b8ecbd-cf3e-4237-be83-a74ab881dbd0

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Sushanth-Hebri** [comment]
Hey , this issue is already solved under issue #50 and PR is merged under #51.

**Comment by brishtiGitH** [comment]
@Sushanth-Hebri Hey, I was just checking out the issue, seems the problem is still there.

**Comment by Sushanth-Hebri** [comment]
**@brishtiGitH Deployment is not updated in Vercel i guess, if you are referring the link.**
Try to run locally it works .

![image](https://github.com/Open-Source-Chandigarh/Euphoria-Check/assets/117469085/b827ee74-de8a-4d16-9ede-7c1dc87f58c0)
![image](https://github.com/Open-Source-Chandigarh/Euphoria-Check/assets/117469085/09ca0b3b-653a-488a-bcc3-52258a166d3a)
